#!/bin/bash

./time "startend-5concurr-plain-nolock.txt" "start"

./concurrent-timings & (sleep 0.5 && ./concurrent-timings) & (sleep 1 && ./concurrent-timings) & (sleep 1.5 && ./concurrent-timings) & (sleep 2 && ./concurrent-timings)

./time "startend-5concurr-plain-nolock.txt" "end"

echo "Complete"
