#!/bin/bash

./time "startend-15concurr-nolock.txt" "Start"

./concurrent-timings & (sleep 0.5 && ./concurrent-timings) & (sleep 1 && ./concurrent-timings) & (sleep 1.5 && ./concurrent-timings) & (sleep 2 && ./concurrent-timings) & (sleep 2.5 && ./concurrent-timings) & (sleep 3 && ./concurrent-timings) & (sleep 3.5 && ./concurrent-timings) & (sleep 4 && ./concurrent-timings) & (sleep 4.5 && ./concurrent-timings) & (sleep 5 && ./concurrent-timings) & (sleep 5.5 && ./concurrent-timings) & (sleep 6 && ./concurrent-timings) & (sleep 6.5 && ./concurrent-timings) & (sleep 7 && ./concurrent-timings)

./time "startend-15concurr-nolock.txt" "End"

echo "Complete"
