#!/bin/bash

./time "startend-100concurr-nolock.txt" "Start"

./run-20-concurr & (sleep 10 && ./run-20-concurr) & (sleep 20 && ./run-20-concurr) & (sleep 30 && ./run-20-concurr) & (sleep 40 && ./run-20-concurr)

./time "startend-100concurr-nolock.txt" "End"

echo "Complete"
