#!/bin/bash

#./time "startend-10concurr-nolock.txt" "start"

./concurrent-timings & (sleep 0.5 && ./concurrent-timings) & (sleep 1 && ./concurrent-timings) & (sleep 1.5 && ./concurrent-timings) & (sleep 2 && ./concurrent-timings) & (sleep 2.5 && ./concurrent-timings) & (sleep 3 && ./concurrent-timings) & (sleep 3.5 && ./concurrent-timings) & (sleep 4 && ./concurrent-timings) & (sleep 4.5 && ./concurrent-timings)

#./time "startend-10concurr-nolock.txt" "end"

#echo "Complete"
