#!/bin/bash

./time "startend-10concurr-plain-nolock.txt" "start"

./concurrent-timings & (sleep 2 && ./concurrent-timings) & (sleep 4 && ./concurrent-timings) & (sleep 6 && ./concurrent-timings) & (sleep 8 && ./concurrent-timings) & (sleep 10 && ./concurrent-timings) & (sleep 12 && ./concurrent-timings) & (sleep 14 && ./concurrent-timings) & (sleep 16 && ./concurrent-timings) & (sleep 18 && ./concurrent-timings)

./time "startend-10concurr-plain-nolock.txt" "end"

echo "Complete"
